### ISSUE TITLE
Font.Render cleanup

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#135]
Each time we use the `font.Render()` function to generate a `Texture`, the texture data is sent to the GPU. 

However, if the text we want to render, changes, the old `Texture` can be removed, if it's replaced by the new one. 

I am not sure what the best-practice is here; possibilities:
* `texture.Delete()` to be called whenever you're replacing the rendered text. 
* Create some kind of wrapper, called `Text`, which contains a reference to the correct font etc., and can be used to `Render` whenever the text-value changes, and removes the old `Texture` automatically. 

Thoughts @paked? We should do something, because this is leaking GPU memory.

**Comment by paked** [comment]
`Text` is already a wrapper for `Font`. I don't think we need another one. If this behaviour should happen at the `Font` level, do so.

**Comment by EtienneBruines** [comment]
We don't have something of type `Text`?

**Comment by paked** [comment]
@EtienneBruines Looks like I implemented it, and then removed it at some point?

It definitely looks like something that should be implemented, as https://github.com/paked/engi/blob/master/demos/pong/pong.go#L266-L276. Does not look that great at all.

Ignore that previous message, implement it at the `Font` level... I'll create a wrapper once this Pull Request is through (I actually have time now, since holidays)

**Comment by EtienneBruines** [comment]
Looking back at this issue; I believe we need some kind of cleanup-function for `Texture`s, not render-things specifically.
