### ISSUE TITLE
Scale entire game

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#270]
> Harrison Shoebridge @paked 01:01
> Something else to consider: someone might want to run their game at 2x scale
> (particularly common for pixel-art based games)

**Comment by mewmew** [comment]
Ebiten does this, and personally, I love having this option present. Specifically when writing games for 640x480 screens : )

**Comment by EtienneBruines** [comment]
Different scaling options for the `X` and `Y` axis?

**Comment by paked** [comment]
@EtienneBruines yes.

**Comment by paked** [comment]
@EtienneBruines yes.

**Comment by hamid-elaosta** [comment]
Since the concept is already used, it would make sense to use `engo.Point` for the scaling which can be independent as desires for `X` and `Y`.

I have managed to get partial scaling by adding a Scale value to the SpaceComponent, however, when my Hero reaches the middle `X` or middle `Y` coordinate, the map jumps to that position. 

For example, if my map starts at `0,0` and is width `256,256`. When my character reaches `128,128` the map tiles jump and are now rendered starting at `128,128`.

Presumably there are a few things in the background that needs more scaling applied.

**Comment by hamid-elaosta** [comment]
I managed to correct this also by adding a Scale value to `Level ` so that when it returns `Bounds` it multiplies them by the scale factor and so the `TrackingBounds` are correct.
