### ISSUE TITLE
data oriented design

### ISSUE THREAD

**Issue by guybrush** [EngoEngine/engo#299]
sorry if this is the wrong place for this issue, wasn't sure if i should post it in ecs or engo.

in `demos/pong` for example you allocate

```
type Ball struct {
	ecs.BasicEntity
	common.RenderComponent
	common.SpaceComponent
	common.CollisionComponent
	SpeedComponent
}
```

in that example its really not that important for sure, since there is only one ball. but in general wouldn't it be better to advertise a data-oriented data-structure somehow? like every component should be put in its corresponding array?

eg:

```
type RenderComponents []common.RenderComponent
type SpaceComponents []common.SpaceComponent
type Ball struct {
	ecs.BasicEntity
        *common.RenderComponent
}
```

but i am not sure at all, this is just a question! i am not sure how exactly golang-memory-allocation works and if its even worth to optimize into that direction. all the resources (articles, videos, ..) about ecs they mention that cache is king?

at least in the pong-example the balls would be spread all around the heap, isn't it?

edit: i am also not sure, what would be the best way to point from the entity-component to the position in the component-array. i think a pointer just wont work, it would have to be some extra field containing the entity-id? like `type Component interface { GetEntityId() EntityId }`

**Comment by EtienneBruines** [comment]
Well,

```go
type Ball struct {
    ecs.BasicEntity
    common.RenderComponent
    common.SpaceComponent
    common.CollisionComponent
    SpeedComponent
}
```

So `Ball` is a type. One that we can instantiate as often as we'd like. In ECS (at least our implementation), there is no "global list" of entities. Each `System` will keep track of the `Component`s it requires (by reference), and whenever `world.Remove` is called, all Systems should remove such reference. The garbage collector will then do the rest. 

The balls would indeed be spread all over the heap. We haven't hit any performance bumps yet (at least not real-world scenarios). As soon as we do, we'll probably look into it. 

Pointing something inside an array, slice or map is indeed pretty much impossible / unreliable. 

Don't get me wrong, but it took us a while to get at this implementation, and it's by far the most performant we could think of. 

(If you wanted to create a million balls (because that's what it takes to get performance issues), then you could simply do `balls := make([]Ball, 1000000)` and you're done. You should add them all to systems etc., but then you have 1000000 balls next to each other in memory.

**Comment by guybrush** [comment]
right, i am glad that you got exactly what i was asking :D 

in the 1mio balls example you are referring to, how could one implement removing and adding entities? i mean you would have to pass the index of the corresponding ball so you can remove it? this becomes especially a hard problem when you sort the balls by position for collision-algorithms.

but i guess if one does not hit a performance-issue one should not pre-optimize?

**Comment by EtienneBruines** [comment]
> but i guess if one does not hit a performance-issue one should not pre-optimize?

Optimizations are always welcome, but will probably not be on our priority list :smile: 

> how could one implement removing and adding entities

This depends on your use-case. The `RenderSystem` for instance, is currently linear (so a slice/array). It would probably be better if it uses quadtrees or something similar. Depending on those implementations, adding / removing them would become different. 

> i mean you would have to pass the index of the corresponding ball so you can remove it?

Yes, when removing something, all you know is it's ID. 

> this becomes especially a hard problem when you sort the balls by position for collision-algorithms.

Well, you can sort any way you like. You don't even have to "actually" remove something when the `Remove` method is called. You could for instance keep a list of ID's you want to remove (sorted by value), and then loop over that on the next `Update` call to remove them (binary search). 

There's a lot of room for performance optimizations, but those are only possible within the actual implementations of the specific systems. `ecs` is now very lightweight, to produce as little overhead as possible. 

Btw, you can always join us at [gitter](https://gitter.im/EngoEngine/engo), or pm me at [Slack](https://gophers.slack.com). :smile:

**Comment by guybrush** [comment]
nice i will idle gitter, feel free to close this issue!

**Comment by EtienneBruines** [comment]
If you ever need anything, don't hesitate to ask :smile:
