### ISSUE TITLE
CameraSystem cleanup

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#318]
As @TheBerryBeast noted, the `RenderSystem` adds a `CameraSystem` if one isn't present yet. 

However, users could add one _right after_ adding the `RenderSystem` - this will not work (nor will it ever). We should find a way to handle this. Perhaps letting the `RenderSystem` crash if no `CameraSystem` was added before adding the `RenderSystem`? That would require everyone to explicitely add the `CameraSystem`, but will also prevent people from accidentally adding it afterwards, thinking it'll work. 

Any thoughts, workarounds or suggestions are welcome - from anyone.

**Comment by paked** [comment]
I think we could take some inspiration from [negroni](https://github.com/urfave/negroni) and have an "add default systems" sort of function. `common.DefaultSystems(w *World)` or something?

The function would add all of the "recommended systems" in the correct order. This might be worth moving to another issue as it doesn't completely fix this one.

**Comment by Noofbiz** [comment]
I don't see any problem with the `RenderSystem`, or any `System`, automatically adding other systems they require so long as those systems have no entities. The real issue here is attempting to add multple `CameraSystem`s, since a game can only have one camera. I think we should check at `CameraSystem.New()` if there's more than one, and then panic if there is. We should also update the documentation for the `RenderSystem` to say that it adds a `CameraSystem` if one is not present as well as documentation for the `CameraSystem` to say that it panics if more than one `CameraSystem` is added to the `World`. Maybe have the panic mention that `RenderSystem` automatically adds a `CameraSystem` so people will see that and go "oh."
