### ISSUE TITLE
engo.Files.Register extension including dot

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#324]
We should allow for extensions including dots. 

You could i.e. register something for `.level.yaml`, and another one for `.monster.yaml`, etc.

Easily implemented using the `strings.HasSuffix` method. 

Up for grabs.

**Comment by madwizard** [comment]
What is the current scope of help you need with it?

**Comment by Noofbiz** [comment]
Should be pretty straightforward, just needs to change the function for formats.load (assets.go line 62)  to get ext using regexp instead of filepath.Ext()

**Comment by Noofbiz** [comment]
The regex would look something like [this](https://regexr.com/2vckg)

**Comment by nishchayp** [comment]
Hi, I'm new to this project and open source contributions in general. Could I please attempt to resolve this issue if it is still relevant.
I was thinking of modifying the 'Ext' function as given in the source code [here](https://golang.org/src/path/filepath/path.go?s=6131:6159#L207) to allow for extensions with `.` in them. I tried something in Go playground [here](https://play.golang.org/p/kr2aO_jypUu) which might work.

**Comment by Noofbiz** [comment]
Yeah that's how it works currently. The issue is that, say you wanted all your monster declaration files to be troll.monster.yaml and ogre.monster.yaml etc but then you had, say, items you wanted like sword.item.yaml and axe.item.yaml

With ext, all of them would be treated as .yaml files since that's the extension, so whichever file loader deals with .yaml will handle both of them.

The way to do this would be to use a regex like `\.(?:.)+$` which will start at the first . and then take everything to the end of the word. I would use the package regexp, and at the start of the load function I would something like this at line 62 of assets.go

```go
regex, err := regexp.Compile("\.(?:.)+$")
if err != nil {
    return err
}
ext := regex.FindString(url)
```

If you'd like to try that or have your own solution, I'd be happy to review any PRs you have. If you have any other questions feel free to ask ^_^

**Comment by Noofbiz** [comment]
Looks good to me, but wouldn't it be easier to read the string left to right and just finding the first `.` then taking the rest of the string?

**Comment by nishchayp** [comment]
Hey, thank you so much for the help and feedback. Makes it a lot easy for newbies to contribute with such a welcoming community :sparkles: I'll work on the PR and get back to you ^_^

**Comment by nishchayp** [comment]
A clarification please. The assets.go file has 3 more instances of `filepath.Ext()` namely on line 89, 98 and 107. I believe they too should be similarly replaced with the modified func to allow for extensions with dot in them. Please let me know if I'm wrong about this.
