### ISSUE TITLE
Remove "ECS" branding

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#331]
From [gitter](https://gitter.im/EngoEngine/engo):

> @paked 09:15 Thoughts on removing ECS from our branding?
> @paked 09:16 I have a theory some people are intimidated by the idea of "using ECS"

Thoughts everyone?

Basically I'd like to make us a "game engine", not an "ECS game engine" - even though we will still use ECS under the hood, and the users will still interact with it.

**Comment by mewmew** [comment]
Some ideas from *the other camp*.

I discovered and became interested in Engo specifically because it was advertised as an ECS game engine. Personally I see the focus on a specific paradigm as a strength, which help guide design decisions and gives a frame of reference from which the project may be evaluated.

That being said, there may be other users who feel intimidated by the ECS paradigm. Do we have any concrete examples of this being the case?

**Comment by EtienneBruines** [comment]
I personally like the idea of *using* ECS. We might be able to say we use ECS, but also mention it's the default/best-practice. And not make a big deal out of it.

**Comment by paked** [comment]
@mewmew We've seen a few people who join the chat and there biggest point-of-failure with Engo is this seemingly abstract concept of ECS.

@EtienneBruines This sounds like the best solution.

**Comment by otraore** [comment]
After hearing out @mewmew and @EtienneBruines I think like @paked I agree with @EtienneBruines as well which takes both sides into consideration.

**Comment by paked** [comment]
@otraore @EtienneBruines @mewmew How do we want to proceed with this issue? I guess we should just start going through things and adapting them to @EtienneBruines's approach...

**Comment by otraore** [comment]
@paked I'd think documentation/tutorials would be the best way to go.

**Comment by mewmew** [comment]
> @paked I'd think documentation/tutorials would be the best way to go.

Definitely, try to ease newcomers into the ECS paradigm, by presenting very clear and educational documentation and tutorials, which help build this understanding in small and digestible steps. Introduce the notion of entities, components and systems as part of the tutorial series, and before the newcomers realise it, they too will be hooked no the ECS paradigm ;)

**Comment by Sendoushi** [comment]
I actually feel a bit intimidated by ECS. I don't know if it is because of that but I do think I prefer to use another pattern or even make my own.

I would do an `engo-core` and then you could have `engo-esc`. This way the framework wouldn't be limited to just one pattern. This may envolve a lot of work though.

**Comment by otraore** [comment]
@Sendoushi I disagree and engo-core and engo-esc. Also the framework isn't limited to one pattern, it's why we seperated engo.io/engo (core) and engo.io/common (ecs implementation) as we've described [here](https://github.com/EngoEngine/engo#theory-common-vs-engo)

**Comment by Sendoushi** [comment]
@otraore Since you still need Scene, World and Systems... There is still ecs implementation. Not entirely separated.

**Comment by Sendoushi** [comment]
It seems that there are only two lines that don't let me use another pattern:
- https://github.com/EngoEngine/engo/blob/master/scene.go#L18 : What if that ecs.World was some kind of interface? Or even... What if there wasn't a world?
- https://github.com/EngoEngine/engo/blob/master/engo_glfw.go#L207 What if this was simply a Mailbox.dispatch and whoever wants to listen...

Scene still makes sense in most of the patterns. It already is an interface. It wouldn't be hard to have those outside also though. Like for example:
- https://github.com/EngoEngine/engo/blob/master/engo_glfw.go#L228 It could be another dispatch

Just some examples of what it could be done...

**Comment by paked** [comment]
My thoughts from gitter related to @Sendoushi's:
![screenshot 2016-06-17 14 23 13](https://cloud.githubusercontent.com/assets/8407370/16140742/2446fcee-3497-11e6-9388-686ba5615289.png)

I'm personally pro making engo open to other other libraries and moving in the direction of a library, as opposed to a highly opinionated engine.

**Comment by faiface** [comment]
I would like to show one precise problem that prevented me from using Engo in my game.

In a game that I'm working on, I have to maintain two copies of the same world and be able to update one of them independently of the other one and also be able to synchronize them (copy from one to another, so that they are same).

I found it hard to implement in Engo (at least for the first 30+ minutes of me trying to implement it), since Engo creates an *ecs.World for me that is hard to copy. I can choose to ignore that world, but that's ugly and you know, I'd have to ignore half of the library then.

So, in my experience, it's actually the ECS (or at least the way Engo implements it) that prevented me from using Engo and made me start developing my own library.

**Comment by paked** [comment]
@faiface: Do you think that Engo could provide more value to people if it was not so opinionated?

**Comment by faiface** [comment]
@paked Possible, but I am not entirely sure about that.

If it was up to me to redesign Engo to perfectly fit my needs, I would probably redesign it to look exactly like the library I'm working on (Pixel, almost ready for alpha release). But it's no point of having two libraries that work exactly same.

So, I that Engo could get better in two ways.
1. Begin less opinionated and more of a library, but that is related the previous paragraph.
2. Improve the ECS so that it is super easy to use and more flexible.

Regarding the second option, I haven't thought of the exact redesign of ECS in Engo, but what I'd definitely address is:
1. Inability to have multiple worlds and interact between them.
2. Need for manual registration of entities to systems. I think this decreases flexibility, productivity and ease of use.

**Comment by Noofbiz** [comment]
I'm thinking in scene we could use an interface called Updater that requires Update(dt), and then in the demos and when utilizing common, you can cast the Updater as an ecs.World to access the fields and methods on that. This way it'll be easy to implement a non-ecs update method, and to utilize engo without needing either ecs or common. You could also implement your own updater that uses multiple interacting worlds, or whatever your needs may end up being.

**Comment by EtienneBruines** [comment]
SGTMOn Mar 7, 2018 6:12 AM, Noofbiz <notifications@github.com> wrote:I'm thinking in scene we could use an interface called Updater that requires Update(dt), and then in the demos and when utilizing common, you can cast the Updater as an ecs.World to access the fields and methods on that. This way it'll be easy to implement a non-ecs update method, and to utilize engo without needing either ecs or common. You could also implement your own updater that uses multiple interacting worlds, or whatever your needs may end up being.
