### ISSUE TITLE
Go Get Problem

### ISSUE THREAD

**Issue by powelles** [EngoEngine/engo#337]
When typing `go get -u engo.io/engo` I get the following error:

```
../engo.io/engo/math.go:10: cannot assign to glm.Epsilon
../engo.io/engo/math.go:10: cannot use 0.001 (type float64) as type untyped number in assignment
../engo.io/engo/math.go:82: undefined: glm.FloatEqual
```

System Info:
- iMac: OS X El Capitan: Version 10.11.5 (15F34)
- go version go1.6 darwin/amd64

I get the same error when I try to run the engo hello world as well.

**Comment by paked** [comment]
@powelles I'm really sorry about this, one of our dependencies broke yesterday. In order to prevent this from happening again in the future we're going to begin pseudo-vendoring the library, you can see this being worked on in #336.

Until we get #336 merged you will have to update `engo` manually.

- `cd $GOPATH/src/github.com/luxengine/glm`
- `git checkout 6a078d911a52a4a4fd9de1fef52a144b98345791`
- `cd $GOPATH/src/engo.io/engo and git pull`

Hopefully the fix will be in over the next few hours.

**Comment by powelles** [comment]
That worked for now. Thanks.

**Comment by otraore** [comment]
Fixed by: https://github.com/EngoEngine/engo/pull/336

**Comment by paked** [comment]
:tada:
