### ISSUE TITLE
Rectangle Border seems not to be drawn correctly?

### ISSUE THREAD

**Issue by countcb** [EngoEngine/engo#408]
When drawing a rectangle with a border there seem to be pixels missing in the corners as seen in this image (ignore the circles):

![image](https://cloud.githubusercontent.com/assets/3466449/23275175/c01c151c-fa05-11e6-907f-1a1aeadcd5a3.png)

Code:

	rectangle1 := MyShape{BasicEntity: ecs.NewBasic()}
	rectangle1.SpaceComponent = common.SpaceComponent{Position: engo.Point{500, 200}, Width: 200, Height: 200}
    rectangle1.RenderComponent = common.RenderComponent{Drawable: common.Rectangle{BorderWidth: 10, BorderColor: color.RGBA{255, 255, 100, 255}}, Color: color.RGBA{255, 255, 100, 255}}

	rectangle2 := MyShape{BasicEntity: ecs.NewBasic()}
	rectangle2.SpaceComponent = common.SpaceComponent{Position: engo.Point{500, 500}, Width: 200, Height: 200}
	rectangle2.RenderComponent = common.RenderComponent{Drawable: common.Rectangle{BorderWidth: 10, BorderColor: color.RGBA{1, 255, 0, 255}}, Color: color.RGBA{1, 255, 0, 255}}

**Comment by otraore** [comment]
I've reproduced this error, looking into it now.

**Comment by Noofbiz** [comment]
So, I've seen several answers to what appears to be this exact problem in several places, https://www.opengl.org/discussion_boards/showthread.php/168187-Missing-pixel-at-rectangle and the links in the comments. Basically, you just offset the modelview matrix by half a pixel or so. Since the target ogl includes ES and web I couldn't use the matrix stack stuff, but emulated it using the glm  library here https://github.com/EngoEngine/engo/compare/rectangle-corners but the corners are still missing those pixels. Any suggestions about how to go about this?

**Comment by Noofbiz** [comment]
https://www.opengl.org/discussion_boards/showthread.php/163522-Drawing-a-framed-rectangle found this. I'll try it out myself when I get time.
