### ISSUE TITLE
Window resize problem

### ISSUE THREAD

**Issue by matiux** [EngoEngine/engo#452]
Hi, I have a window of 1024 x 768
I have setup also MouseSystem so when window is created, the left side has X 0 coodinate.
If I narrow the window and put the mouse arrow on te left side, the X coordinate is no longer 0 but, for example 150. Is like if 0 cordinate, shifts left. But I need to have 0 always on left border side

**Comment by matiux** [comment]
Update:
I have implemented a listener for WindowResizeMessage
```
	engo.Mailbox.Listen("WindowResizeMessage", func(msg engo.Message) {

		winResMessage, ok := msg.(engo.WindowResizeMessage)
		if !ok {
			return
		}

		//difW = winResMessage.NewWidth - winResMessage.OldWidth
		//difH = winResMessage.NewHeight - winResMessage.OldHeight

		fmt.Println(winResMessage.NewWidth, winResMessage.OldWidth)

	})
```

I don't understand because winResMessage.NewWidth and winResMessage.OldWidth are always equals. It's normal?

**Comment by Noofbiz** [comment]
I've actually been working on this in #449 and #428. The pull request is #451. What is happening is when the window is resized, the space coordinates are keeping their positions and the camera is expanding around it, thus creating an offset between the original coordinate system and the updated one. 
The reason the window size is giving you that message is because it's updated in a callback on resize, so it changes when he window is resized to give you the same size both times. Due to this, things like the canvas scale also end up being 1 practically all the time.

**Comment by matiux** [comment]
Thanks @Noofbiz 
how can I use your commit to fix the problem?

**Comment by Noofbiz** [comment]
The new commit adds a variable engo.ResizeXOffset as well as a Y version. Subtract half that off the entity's space component if you want it to stay the same on resize. You can also use one of  the HUD shader to get the same effect.

**Comment by Noofbiz** [comment]
The commit has been added to master, so you can use the offsets to adjust your positioning. Feel free to reopen this or ask something else if you need to.
