### ISSUE TITLE
Possible RunOption: Resizable windows

### ISSUE THREAD

**Issue by dstewart** [EngoEngine/engo#466]
I have played some 2D games such as Owlboy where the windows are not resizable in widowed-mode. I was able to achieve this by adding the following lines just before engo.Run():

`glfw.Init()`
`glfw.WindowHint(glfw.Resizable, glfw.False)`

Users who are not familiar with GLFW may just want to flag a Resizable field in RunOptions or something like that. Just a suggestion.

**Comment by otraore** [comment]
I like the idea, do you want to be the one to add it in @dstewart? You can start by looking at [this file](https://github.com/EngoEngine/engo/blob/master/engo.go) and set a variable that'll be checked on window creation [here](https://github.com/EngoEngine/engo/blob/master/engo_glfw.go#L48) and run that since it's only on glfw.

**Comment by Noofbiz** [comment]
This is actually already done in PR #459
