### ISSUE TITLE
VBO?

### ISSUE THREAD

**Issue by aubonbeurre** [EngoEngine/engo#470]
HI,

I'm interested to add VBO support for GL. Can... I... just do that? Any word of wisdom? Thanks!

./vbo.go:22:10: engo.Gl.DeleteBuffers undefined (type *"engo.io/gl".Context has no field or method DeleteBuffers)
./vbo.go:25:10: engo.Gl.DeleteBuffers undefined (type *"engo.io/gl".Context has no field or method DeleteBuffers)
./vbo.go:28:10: engo.Gl.DeleteVertexArrays undefined (type *"engo.io/gl".Context has no field or method DeleteVertexArrays)
./vbo.go:34:9: engo.Gl.BindVertexArray undefined (type *"engo.io/gl".Context has no field or method BindVertexArray)

**Comment by Noofbiz** [comment]
Most of the stuff is written to support WebGL and OpenGL ES 2.0 due to trying to support mobile and web. If you don't want either of these targets, you can use a custom shader and a separate graphics library. Just make sure your shader implements the Shader interface

type Shader interface {
	Setup(*ecs.World) error
	Pre()
	Draw(*RenderComponent, *SpaceComponent)
	Post()
}

and then use a graphics library other than engo.io/gl such as go-gl
https://github.com/go-gl/gl. Then you can use that shader. 
These functions definitely won't work for android/ios building, and probably won't work for web builds either, just as a warning.

They have an example here:
https://github.com/go-gl/example/blob/master/gl41core-cube/cube.go
that should work as I described above. Just put the setup/pre/draw/post stuff in the right places. The glfw setup is done by engo already, so you can skip to about line 49-ish

**Comment by aubonbeurre** [comment]
Thanks @Noofbiz for the long answer. Admittedly I was more interested to start a discussion, please consider this issue closed.

I'm interested to run gomobile and WebGL with OGL 3. It seems WebGL should support it, no? I could not try that, because I did not find an example of a suitable index.html that would exercise my engo sample using VBO.

As for gomobile, I hacked it to add VBO, and took the time to fill a review to google (see https://go-review.googlesource.com/c/mobile/+/61370): it almost works! Except gomobile is not using a recent Android SDK, the emulator seems to choke with ES 3, etc...

So all together I was able to convince myself engo could get OGL4/ES3 support in the future (except for WebGL due to lack of understanding of the engo binding), which would entail for using VBO, FBO in the future... And make things more fun :)

I took on your idea to make my own RenderComponent, and by hacking glfw setup, I was able to render inside a 4.1-core GL on desktop (and almost of Android).

Anyway, I had fun playing with engo today!

**Comment by Noofbiz** [comment]
I actually agree that the shaders and render system should be updated eventually to handle these, especially vbo and vao, but also other helpers like ortho would be nice to have. We've had a few people open requests for these functions before. 

As far as web gl goes try gopherjs serve and on local host, and I download android studio entirely for the emulator. Works okay for me. Haven't tried es3 on it though. To target a higher sdk just change it in the manifest rather than just the default gomobile one.

**Comment by aubonbeurre** [comment]
Here is what it looks like to switch to OGL4.1/ES3: https://github.com/aubonbeurre/gl/commit/d38d510fb184e78e0bf044ad62a187108c5d0373

Thanks, I will play with gopherjs serve!
