### ISSUE TITLE
Hi,Author,I have a advice.

### ISSUE THREAD

**Issue by Think-Jumper** [EngoEngine/engo#504]
Hi,Author,I have a advice.I think Go is design for network's works.Why not make it for more sense at its field? How about convet Engo into a special，professional ，light weight game server engine, such as html5 game's universal server. Display on webpage but not on native application which Go is not good at.It's a tiny tiny tiny advice. My english is not very well. Just a TuCao. Never mind,please.

**Comment by umarquez** [comment]
Actually you can use **Engo** as a _"server side game engine"_; it is not necessary to render anything or play any sound to run a game logic engine; also you can follow the _ECS_ pattern that **Engo** implements and used it in a multiplayer engine to keep syncronized the playe's states.

And talking about **HTML**, you can use **Engo** in the browser because of [**gopherjs**](https://github.com/gopherjs/gopherjs), you can read it [here](https://github.com/EngoEngine/engo#engo):

> Web support (gopherjs) is also available.

**Comment by Asday** [comment]
Go is perfectly good at running as a native app.  See [wxGo](https://github.com/dontpanic92/wxGo) and [pixel](https://github.com/faiface/pixel).

**Comment by Noofbiz** [comment]
`engo` can be used as the server-side implementation, you'd really just need EngoEngine/ecs to do it, whereas `engo` itself is a traditional game engine on top of the ecs implementation. I believe in gitter @mischief was talking about such an implementation. Maybe he has more insight into such an implementation, but you're right that the ecs paradigm should work extremely well as a game server.

**Comment by Think-Jumper** [comment]
@umarquez I had try out the gopherjs on PC browser and many mobiles' browser.It's not universal.If I write a _server side game engine_ use Go and need to convert to javascript,why not I use javascript to write it directly?But thank you all the same for your suggestion,it will be used when gopherjs mature engouh in real production environment. @Asday Thank you for expanding my knowledge about Go's usage(Execuse my ignorance). @Noofbiz I had use Engo's ECS that Engo implements to write something tiny toy last year or maybe longer before and it works productive to code something funny so that make me want to tell you this tiny tiny tiny advice about Engo when I didn't know there were already have some native applications write with Go althouth I don't know if these could be use in real production environment at that time. Thank you for take some time to reply my doubt.

**Comment by umarquez** [comment]
@Think-Jumper Why did you said you need to convert your server side code to JS?
What I was mean was that you could implement Engo in the browser using gopherjs.
Go is perfect for coding multiplayers engines that runs from the compiled executable in the server side, it doesn't need to be converted to JS neither to be running in the browser.

**Comment by Think-Jumper** [comment]
I mean that gopherjs will complie Go into pure JS then the pure JS run on browser. The browser can not run the Go complied executable directly.It's not doubt that  _Go is perfect for coding multiplayers engines that runs from the compiled executable in the server side_，but it's not Explicit, Indirect ,isn't it ?

**Comment by Asday** [comment]
What you're suggesting is a reasonably large change to the project that would remove functionality, for less than zero benefit.

If you personally see value in it, then that's good for you, but it would be to the detriment of the rest of the community, so by all means, fork Engo and make the changes for your own purposes.

From what I can gather, though, ECS will do what you need already.

**Comment by Think-Jumper** [comment]
before i offer my suggestion, its all basic on original idea of the creator , who design and create the GO.All my thought and consideration is from that.The community is not in my consideration.This is about the trend of GO. it's not about the community. As far as we all know,the community have tremendous influce on certain things.but everything have its own developing trend, i just suggest we can choose the direction which have more possibility.

**Comment by Asday** [comment]
Engo has 36 contributors, 43 people watching the repository, and 700+ stars.  It is doing absolutely _fine_ without completely gutting itself and removing functionality as you want it to do.

Like I said - make your own fork.  If it's so much better an idea, your fork will surpass this, no?

**Comment by Think-Jumper** [comment]
。。。。。。Ok. It's just a advice.That's all.

**Comment by paked** [comment]
Hey everyone.

I'm going to go ahead and close this issue, since it doesn't contain an outstanding bug, feature request or Engo related support query. Feel free to re-open if I've missed something (cc: @Noofbiz).

@Think-Jumper: I thank you for your suggestion, but I don't think it's something the current Engo team (I'm barely that) will be taking on board -- but of course it's up to them to decide what to do. From my perspective, it would represent a drastic change in direction for the engine and probably a completely from ground up rewrite.

I definitely think there is value in someone creating an open source server side game engine in Go, and would happily encourage you to start hacking on it on your own solution. I'm sure if you asked on our Gitter you could even find someone else to help coding the first version.
