### ISSUE TITLE
FPS drops a lot after adding a common.AudioSystem

### ISSUE THREAD

**Issue by hismito** [EngoEngine/engo#589]
After adding a `common.AudioSystem`, fps drops from 500+ to around 20.

[Demo code](https://gist.github.com/hismito/ca03e72bd3fef38c708da111a43d22ab)
Go version: go1.11.1 darwin/amd64
Engo version: engo.io/engo v0.0.0-20181013012526-3126f2cb9ec7
OS: macOS 10.12.6

**Comment by Noofbiz** [comment]
Thanks for finding this. I believe it has something to do with writing nothing to oto, since no players are added to the system. I don't think it's been tested without any music playing.

I never noticed such a huge frame drop in my game, it was running at 60 on desktop and 30 on android while playing music. I'll take a look when I can. Thanks, again, it's a great find!
