### ISSUE TITLE
Separate engo math stuff from repo

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#591]
The stuff in `engo.io/engo`'s math.go file should be separated from the rest of engo so that people can use things like AABB and Point without all the graphics and input dependencies in the main repo. I think it could go in `engo.io/engo/math` pretty easily. However, that package is supposed to be a drop-in for the standard library's math package. Might be better to work on our glm package and make that production ready but that will take more time.

**Comment by foxinni** [comment]
Two ways to look at it: Change the API early to accommodate for this without having special build scripts (seeing that you might have spotted a limitation early). **OR** keep things like they are if you don't believe it's written wrong and add post processing.

Added to that, the headless build seems better, because when I do run the app locally, I like the fact that I have a UI to interact with. In essence "seeing" what the server is doing in real time. If you had to yank out the GL/Graphics stuff it could be difficult/impossible to get it back in if you wanted to run a GUI version locally.

Thus I'm in favour of "headless" build tag from my limited view.

**Comment by Noofbiz** [comment]
Closed by #592
