### ISSUE TITLE
I cant get it running.

### ISSUE THREAD

**Issue by jakubDoka** [EngoEngine/engo#718]
When i import the "github.com/EngoEngine/engo" or any other package i get error message : 
# github.com/go-gl/glfw/v3.3/glfw
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
# github.com/go-gl/gl/v2.1/gl
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
I have no idea what this is and i canot find anything on internet eather.

**Comment by otraore** [comment]
Make sure you have the 64 bit version of the GCC compiler from Mingw-w64. You can get it [here](http://mingw-w64.org/doku.php/start). I'm personally using [WinBuilds](http://win-builds.org/doku.php). It should work after that because that error is usually from you having the 32 bit version installed.

**Comment by jakubDoka** [comment]
In deed i have. Thank you. I probably downloaded 32 by accident.

**Comment by otraore** [comment]
Glad that fixed you issue, let us know if you have any other questions or concerns.
