### ISSUE TITLE
Demo count

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#75]
As @matiwinnetou also mentioned at IRC: it looks like we're going to have a huge amount of demos, if we keep going like this.

-----

What are we going to do about the huge amount of demos?

* Categorize them? (i.e.: audio-related, camera-related, etc.)
* Remove them? (i.e.: only take those most important)
* Merge them? (like in games as pong)
* Better document them in the "main" `README.md` file in the `demos/` directory?
* ...?

------
We can use this issue to keep track of what we  want to do about this (upcoming) problem.

**Comment by paked** [comment]
I'd be down to categorization. I don't think they should be moved into a separate repository. Maybe we should add a better index in `demos/README.md`

**Comment by mewmew** [comment]
> Categorize them? (i.e.: audio-related, camera-related, etc.)
> Remove them? (i.e.: only take those most important)
> Merge them? (like in games as pong)
> Better document them in the "main" README.md file in the demos/ directory?

After having categorized the demos, removing redundant ones should be easy. I would prefer if the demos were kept minimal, to demonstrate a specific aspect of the engine. Otherwise it may be overwhelming for a newcomer. Perhaps the structure and categorization could be provided by the `demos/README.md` file, instead of creating a nested directory structure. This also makes sense, as some demos would demonstrate more than one aspect of the engine, thus making it difficult to categorize in a tree-like fashion.

> I'd be down to categorization. I don't think they should be moved into a separate repository. Maybe we should add a better index in demos/README.md

I also think it is a good idea to keep the demos in the main repo. Otherwise they will be very likely to go out of sync (as is already the case with the TrafficManager tutorial example, which lives outside of the main repo).

**Comment by otraore** [comment]
These are the demos that need to be added to the README.md

- incrementalcamera
- input
- keyboardscroller
- mouse-follow
- mouse
- mouserotation
- rotation
- scale
- scenes
- shapes
- text
- tilemap
