### ISSUE TITLE
Shape drawing problem

### ISSUE THREAD

**Issue by kayon** [EngoEngine/engo#761]
**Circle border**
<img width="500" alt="1" src="https://user-images.githubusercontent.com/5260178/109977478-d3803480-7d37-11eb-95f0-839cb4a6b5b2.png">
`
common.Circle{
	BorderWidth: 1,
	BorderColor: color.Black,
}
`

The border drawing is abnormal. Fill color cannot be transparent. The same goes for running demos/shapes.

**Circle Arc**
`
common.Circle{
	Arc: 180
}
`
<img width="667" alt="2" src="https://user-images.githubusercontent.com/5260178/109977477-d3803480-7d37-11eb-89a7-1bf6e9473b43.png">

**Text**
When there are Chinese characters in the string.
`index out of range ... common.(*textShader).generateBufferContent`

**Comment by eth0net** [comment]
Just been looking through the files for this and I think the issue is coming from lines 273-305 of engo/common/render_shaders_shapes.go

Looks like the circle is being drawn full size in the right place for the border, then drawn again but offset left and up by border width, rather than in the same position but 2*borderwidth smaller.

**Comment by eth0net** [comment]
I found the offset by putting it in the same position as a rectangle of the same width/height to see which part of the circle was wrong.

**Comment by eth0net** [comment]
Just managed to fix the circle issue.

**Comment by eth0net** [comment]
Transparency isn't working with borders, it hides the main layer but the border layers still fills that space too. The border code needs tweaking to only occupy the area around the rest of the shape.

**Comment by Noofbiz** [comment]
Cool beans. The issue with the other two is a bit more challenging sadly. One problem is the number of triangles I'm making the circles out of is 300, which doesn't divide by 180 nicely, so the problem is you'll never get nice flat stuff like that this way. I don't like that, so I think upping the triangles to 360 would be a good idea. That way every whole angle gets a triangle. 
Drawing a transparent circle isn't going to be possible the way I've done it. I'm actually drawing two circles, the border and then the normal circle on top of it. If you make the normal circle transparent, you'll see the border circle underneath! So we're  going to have to either decide transparent circles with borders aren't supported, or draw them using another method.

**Comment by eth0net** [comment]
Okay didn't realise you were using triangles, to be honest, interesting! But yeah I was seeing the issue with the two circles... shame it won't create nice edges, because it would be great if we could just get it to draw between the edge and edge-borderwidth rather than edge and center.
